<?php

require_once(dirname(__FILE__) . '/PaymentAbstract.php');

class PaymentExample extends PaymentAbstract {
	
    public static function getModuleInfo()
	{
		return array(
			'title' => 'Example Payment Method',
			'version' => 001,
			'summary' => 'Demonstrates how to create payment methods for PW Shop',
			'singular' => false,
			'autoload' => false
		);
	}
    public function init() {
		
	}
	
	/*
	 *
	 * returns nothing, should always do redirect to payment processor or if local
	 * then to ../completed/
	 *
	 * @param Page $order keeps the page object for the order
	 *
	 */
    public function processPayment(Page $order) {
		if ($this->input->get->ok) {
			
			
			
			if ($this->input->get->ok == 'fail') {
				// We don't remove statusUnpublished and it means that payment failed
				$this->session->redirect($this->completedUrl);
			}
			
			if ($this->input->get->ok == 'paid') {
				$order->setOutputFormatting(false);
				$order->sc_paid = time();
			}
			
			$order->removeStatus(Page::statusUnpublished);
			$order->save();
			
			$this->session->redirect($this->completedUrl);
			
			
		}
		
		//  No need to really do anything like this on payment module, this is here just for educational purposes):
		$out = "<p>Please review your order</p>";
		$out .= "<h2>Products ordered</h2>";
		
		$out .=	"<ul>";	
		// Products
		foreach($order->children as $p) {
			$out .= "<li><strong>{$p->title}</strong> {$p->sc_price}€ x {$p->sc_qty} (total: ". $p->sc_qty * $p->sc_price ."€)</li>";
		}
		$out .= "</ul>";
		
		$out .= "<h2>Shipping details</h2>";
		
		$out .=	"<ul>";	
		// Products
		$out .= "<li>Fullname: $order->sc_fullname</li>";
		$out .= "<li>Email: $order->email</li>";
		$out .= "<li>Address: $order->sc_shippingaddress</li>";
		$out .= "<li>Country: $order->sc_country</li>";
		$out .= "<li>Username: {$order->sc_customer->name}</li>";
		$out .= "</ul>";
		
		
		
		// Usually we would use some payment api or send people to 3rd party service like paypal
		// and process their reply
		
		$out .= "<h3>How do we proceed?</h3>";
		
		$out .= "<ul><li><a href='./?ok=invoice'>Send me an invoice</a>";
		$out .= "<li><a href='./?ok=paid'>I have already paid this</a>";
		$out .= "<li><a href='./?ok=fail'>I want to fail this payment</a>";
		
		return $out;
    }
}
