<?php

class ShoppingOrdersManagement extends Process {

	public static function getModuleInfo() {
		return array(
			'title' => 'Orders Management',
			'summary' => 'Manage Shop orders',
			'version' => 002,
			'permanent' => false,
			'singular' => true,
			'permission' => 'shop_orders',
			'requires' => array(
								"ShoppingCart",
								"ShoppingCheckout"
								)
		);
	}

	public function init() {
		parent::init();
	}

	public function ___execute() {
		$this->setFuel('processHeadline', 'Manage orders');

		$out  = "<div id='all_orders'>";
		$out .= "<h2>". $this->_("All orders:") ."</h2>";

		$table = $this->modules->get("MarkupAdminDataTable");
		$table->setEncodeEntities(false);
		$table->headerRow(array($this->_('Customer'), $this->_('Status'), $this->_('Total Sum'), $this->_('Time')));

		$orders = $this->pages->find('template=sc-order,limit=20,sort=-created');

		if($orders->count() == 0) {
			$out .= $this->_("No orders yet");
		} else {

			foreach($orders as $order) {

				 // output in table rows with edit link and delete checkbox?
				 $table->row(array(
					 $order->sc_firstname . " " . $order->sc_lastname => "edit/?id={$order->id}",
					 $order->sc_status->title,
					 $order->sc_price . ' &euro;',
					 date($this->config->dateFormat,$order->created)
				));
			}
			$out .= $table->render();
			$pager = $orders->getTotal() > count($orders) ? $orders->renderPager() : '';
			$out .= $pager;
		}
		$out .= "</div>";

		$out .= "<div id='active_carts'>";
		$out .= "<h2>". $this->_("Active carts:") ."</h2>";

		$table = $this->modules->get("MarkupAdminDataTable");
		$table->setEncodeEntities(false);
		$table->headerRow(array('View', 'Total Sum', 'Time'));

		$result = $this->db->query("SELECT * FROM ShoppingCart WHERE total_sum > 0 ORDER BY last_modified DESC LIMIT 10");

		while($row = $result->fetch_assoc()) {

			 // output in table rows with edit link and delete checkbox?
			 $table->row(array(
				 $this->_("View"),
				 $row['total_sum'] . ' &euro;',
				 $row['last_modified']
			));
		}

		$out .= $table->render();
		$out .= "</div>";



		// Is there clean way to add button to right side?
		return $out;
	}

	public function ___executeEdit() {

		$this->fuel->breadcrumbs->add(new Breadcrumb('../', 'Orders'));
		$id = (int) $this->input->get->id;
		$order = $this->pages->get($id);

		if ($id < 1 || $order->template != 'sc-order') return false;

		$out = '';

		// Save processed date
		if ($this->input->post->processed) {
			$order->sc_processed = time();
			$order->save();
		}

		// Save paid date
		if ($this->input->post->paid) {
			$order->sc_paid = time();
			$order->save();
		}

		// Change status
		if ($this->input->post->status) {
			$status = $this->pages->get("template=admin, name={$this->input->post->status}");
			$order->sc_status = $status;
			$order->save();
			$this->session->redirect("./?id=$id");
		}


		$out .= "<div class='sc-header'><h2><span>{$order->sc_status->title}</span> #{$id}</h2></div>";

		$out .= "<div class='customer'><p><b>" .
				$order->sc_firstname . " ".
				$order->sc_lastname ."</b></p><p>".
				$order->sc_streetaddress . "<br />".
				$order->sc_city."</p></div>";


		$table = $this->modules->get("MarkupAdminDataTable");
		$table->setEncodeEntities(false);
		$table->setClass('items');
		$table->headerRow(array($this->_('Product'),
								$this->_('Qty'),
								$this->_('Price'),
								$this->_('Total')));

		$items = $order->children();
		$order_total = 0;

		foreach($items as $item) {

			// get product price from actual product page
			$total_price = $item->sc_qty * $item->sc_price;

			$table->row(array(
			   $item->title,
			   $item->sc_qty,
			   $item->sc_price,
			   $total_price
			));

			$order_total = $order_total + $total_price;
		}

		$table->row(array(
			"<b>" . $this->_("Total:") . "</b>",
			"&nbsp;",
			"&nbsp;",
			$order_total
		));



		$out .= $table->render();

		$out .= "<a class='edit-order' href='". $this->pages->get($this->config->adminRootPageID)->url ."page/edit/?id=$order->id'>". $this->_("Edit this order") ."</a>";


		if($order->sc_paid == 0) {
			$out .= "<div id='paid_container' class='block'><h3>". $this->_("Customer hasn't paid this order yet") ."</h3>";
			$out .= "<p class='description'>". $this->_("Payment method: ") . "<b>" . $order->sc_paymentmethod . "</b><br/>" . $this->_("Mark this paid after you have received the payment.") . "</p>";

			$form = $this->modules->get('InputfieldForm');
			$form->attr('action', './?id=' . $id);
			$form->attr('method', 'post');

			$field = $this->modules->get('InputfieldSubmit');
			$field->attr('id+name', 'paid');
			$field->attr('value', $this->_('Mark as Paid'));
			$form->append($field);

			$out .= $form->render();
			$out .= "</div>";
		} else {
			$out .= "<div id='paid_container' class='block'><h3>". $this->_("This order has been paid") ."</h3>";
			$out .= "<p class='description'>". $this->_("Payment method: ") . "<b>" . $order->sc_paymentmethod . "</b><br/>" . $this->_("Date of payment received: ") . date($this->config->dateFormat,$order->sc_paid) . "</p>";
			$out .= "</div>";
		}

		if ($order->sc_processed == 0) {
			$out .= "<div id='processed_container' class='block'><h3>". $this->_("This order hasn't been processed yet.") ."</h3>";
			$out .= "<p class='description'>" .  $this->_("Mark this processed after you have delivered the goods.") . "</p>";
			$form = $this->modules->get('InputfieldForm');
			$form->attr('action', './?id=' . $id);
			$form->attr('method', 'post');

			$field = $this->modules->get('InputfieldSubmit');
			$field->attr('id+name', 'processed');
			$field->attr('value', $this->_('Mark as Processed'));
			$form->append($field);

			$out .= $form->render();
			$out .= "</div>";

		} else {
			$out .= "<div id='processed_container' class='block'><h3>". $this->_("This order has been processed.") ."</h3>";
			$out .= "<p class='description'>" .  $this->_("This order has been marked processed on: ") . date($this->config->dateFormat,$order->sc_processed) . "</p>";
			$out .= "</div>";
		}

		$out .= "<div id='status_container' class='block'>";
		$form = $this->modules->get('InputfieldForm');
		$form->attr('action', './?id=' . $id);
		$form->attr('method', 'post');

		$container = new InputfieldWrapper();
		$field = $this->modules->get('InputfieldSelect');
		$statuses = $this->pages->get('template=admin,name=statuses')->children();
		$field->attr('id+name', 'status');
		$field->set('label', $this->_("Change order status?"));
		$field->set('collapsed', 1);
		foreach($statuses as $status) {
			if ($status == $order->sc_status) $selected = array('selected' => 'selected');
			else $selected = array();
			$field->addOption($status->name, $status->title, $selected);
		}
		$container->add($field);


		$field = $this->modules->get('InputfieldSubmit');
		$field->attr('id+name', 'changestatus');
		$field->attr('value', $this->_('Change status'));
		$container->add($field);
		$form->append($container);

		$out .= $form->render();
		$out .= "</div>";

		return $out;
	}

	public function install() {


		$orders = new Page();
		$orders->template = $this->templates->get("admin");
		$orders->parent = $this->pages->get($this->config->adminRootPageID);
		$orders->title = 'Manage orders';
		$orders->name = 'manage-orders';
		$orders->process = $this;
		$orders->save();

	}

	public function uninstall() {
		$p = $this->pages->get('template=admin, name=manage-orders, include=all');
		if ($p->id) $this->pages->delete($p, true); // Recursive delete
	}


}
